### ISSUE TITLE
Subdomain limit

### ISSUE THREAD

**Issue by rnc** [timboudreau/tiny-maven-proxy#5]
Attempting to configure with e.g. 
```
mirror=http://foo.cloud.engineering.mycompany.com
```
leads to 
```
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, org.netbeans.validation.api.InvalidInputException: Too many parts in host name or IP address 'foo.cloud.engineering.mycompany.com' (Fatal Error)
  at com.mastfrog.tinymavenproxy.Config.<init>(Config.java:74)
  at com.mastfrog.tinymavenproxy.Config.class(Config.java:74)
  while locating com.mastfrog.tinymavenproxy.Config
    for the 2nd parameter of com.mastfrog.tinymavenproxy.TinyMavenProxy$StartupLogger.<init>(TinyMavenProxy.java:145)
  at com.mastfrog.tinymavenproxy.TinyMavenProxy.configure(TinyMavenProxy.java:120)
  while locating com.mastfrog.tinymavenproxy.TinyMavenProxy$StartupLogger
```

from https://github.com/timboudreau/simplevalidation (specifically line 114 of HostnameValidator).

**Comment by timboudreau** [comment]
Fixed.
